rules = [
  OrganizeImports
]

OrganizeImports {
    groupedImports = Merge
    importsOrder = Keep
    importSelectorsOrder = Keep
    coalesceToWildcardImportThreshold = 3
    expandRelative = true
    removeUnused = false
    groups = [
      "*"
      "scala."
      "re:javax?\\."
    ]
}